from __future__ import annotations

import json
import os
import subprocess
import sys
import time
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
RALPH_SH = REPO_ROOT / "ralph.sh"


def wait_until(predicate, timeout: float = 10.0, interval: float = 0.1) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(interval)
    return False


def write_executable(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    path.chmod(0o755)


def make_fake_binaries(bin_dir: Path) -> None:
    write_executable(
        bin_dir / "codex",
        """#!/usr/bin/env python3
from __future__ import annotations
import json
import os
import subprocess
import sys
import time
from pathlib import Path

args = sys.argv[1:]
review_file = None
prompt = args[-1] if args else ""
i = 0
while i < len(args):
    if args[i] in {"-s", "-m"}:
        i += 2
    elif args[i] == "-o":
        review_file = args[i + 1]
        i += 2
    else:
        i += 1

sleep_s = float(os.environ.get("MOCK_CODEX_SLEEP", "0"))
mode = os.environ.get("MOCK_CODEX_MODE", "success")
marker_file = os.environ.get("MOCK_RATE_LIMIT_MARKER", "")
child_pid_file = os.environ.get("MOCK_CHILD_PID_FILE", "")
prompt_capture_file = os.environ.get("MOCK_CODEX_CAPTURE_PROMPT_FILE", "")
lead_fix_marker = os.environ.get("MOCK_LEAD_FIX_MARKER", "")
write_file = os.environ.get("MOCK_CODEX_WRITE_FILE", "")
write_content = os.environ.get("MOCK_CODEX_WRITE_CONTENT", "// generated by mock codex\\n")
if review_file:
    if mode == "lead_fix_once":
        marker = Path(lead_fix_marker) if lead_fix_marker else None
        if marker is not None and not marker.exists():
            marker.write_text("fix-issued", encoding="utf-8")
            payload = {
                "decision": "fix",
                "quality_score": 4,
                "fix_instructions": "Address the missing acceptance criteria and rerun tests.",
                "progress_note": "Needs one more pass",
            }
        else:
            payload = {
                "decision": "approve",
                "quality_score": 8,
                "progress_note": "Integration test approve",
            }
    elif mode == "lead_mismatch_fix":
        payload = {
            "decision": "fix",
            "quality_score": 3,
            "fix_instructions": "The authoritative review says fix.",
            "progress_note": "Fail closed on mismatched lead output",
        }
        print(
            "```json\\n"
            '{"decision":"approve","task_id":"T01","summary":"Incorrect approve from stdout","quality_score":8,"issues":[],"fix_instructions":"","alert_reason":"","progress_note":"Conflicting stdout review"}'
            "\\n```"
        )
    elif mode == "lead_contradictory_fix_only":
        payload = {
            "decision": "fix",
            "task_id": "T01",
            "quality_score": 2,
            "fix_instructions": "Update tasks.json, update progress.md, add a final commit, and provide a real non-empty git diff.",
            "progress_note": "Bookkeeping-only contradictory fix",
        }
    elif mode == "lead_diff_only_fix":
        payload = {
            "decision": "fix",
            "task_id": "T01",
            "quality_score": 2,
            "fix_instructions": "Prepare a real non-empty git diff and final commit for this task.",
            "progress_note": "Diff-only contradictory fix",
        }
    elif mode == "lead_exact_gap_with_bookkeeping_noise":
        marker = Path(lead_fix_marker) if lead_fix_marker else None
        if marker is not None and not marker.exists():
            marker.write_text("fix-issued", encoding="utf-8")
            payload = {
                "decision": "fix",
                "task_id": "T01",
                "quality_score": 4,
                "fix_instructions": "Add an /audit_task alias that routes to the single-task audit handler and cover it with a bot test. Do not forget to update tasks.json, progress.md, and provide a real git diff.",
                "progress_note": "Needs exact API gap only",
            }
        else:
            payload = {
                "decision": "approve",
                "task_id": "T01",
                "quality_score": 8,
                "progress_note": "Exact gap resolved",
            }
    else:
        payload = {
            "decision": "approve",
            "quality_score": 8,
            "progress_note": "Integration test approve",
        }
    Path(review_file).write_text(json.dumps(payload), encoding="utf-8")
else:
    if prompt_capture_file:
        Path(prompt_capture_file).write_text(prompt, encoding="utf-8")
    if mode == "asset_manifest_wait":
        manifest = {
            "version": 1,
            "generated_by": "coder",
            "assets": [
                {
                    "id": "hero-image",
                    "kind": "image",
                    "request": "Create a hero image for the landing page",
                    "source_path": ".ralph/assets/inbox/hero-image.txt",
                    "target_path": "src/assets/hero-image.txt",
                }
            ],
        }
        Path("assets_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    if mode == "always_fail":
        print("fatal codex failure")
        sys.exit(1)
    if mode == "rate_limit_once":
        marker = Path(marker_file) if marker_file else None
        if marker is not None and not marker.exists():
            marker.write_text("rate-limited", encoding="utf-8")
            print("429 Too Many Requests")
            sys.exit(1)
    if mode == "timeout_child":
        child = subprocess.Popen(["sleep", "30"])
        if child_pid_file:
            Path(child_pid_file).write_text(str(child.pid), encoding="utf-8")
        try:
            time.sleep(30)
        except KeyboardInterrupt:
            pass
    if write_file:
        target = Path(write_file)
        target.parent.mkdir(parents=True, exist_ok=True)
        with target.open("a", encoding="utf-8") as fh:
            fh.write(write_content)
    if sleep_s > 0:
        time.sleep(sleep_s)

print("tokens used")
print("123")
""",
    )
    write_executable(
        bin_dir / "gtimeout",
        """#!/usr/bin/env python3
from __future__ import annotations
import os
import signal
import subprocess
import sys

args = sys.argv[1:]
timeout = None
i = 0
while i < len(args):
    arg = args[i]
    if arg == "--foreground" or arg.startswith("--kill-after="):
        i += 1
        continue
    try:
        timeout = float(arg)
        i += 1
        break
    except ValueError:
        break

cmd = args[i:]
if not cmd:
    sys.exit(1)

proc = subprocess.Popen(cmd)
if timeout is None:
    sys.exit(proc.wait())

try:
    sys.exit(proc.wait(timeout=timeout))
except subprocess.TimeoutExpired:
    if os.environ.get("MOCK_GTIMEOUT_KILL_PARENT_ONLY") == "1":
        proc.kill()
        proc.wait()
    else:
        proc.kill()
        proc.wait()
    sys.exit(124)
""",
    )


def init_git_repo(project_dir: Path) -> None:
    env = os.environ.copy()
    env.update(
        {
            "GIT_AUTHOR_NAME": "Test User",
            "GIT_AUTHOR_EMAIL": "test@example.com",
            "GIT_COMMITTER_NAME": "Test User",
            "GIT_COMMITTER_EMAIL": "test@example.com",
        }
    )
    subprocess.run(["git", "init"], cwd=project_dir, check=True, capture_output=True, text=True, env=env)
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True, text=True, env=env)
    subprocess.run(
        ["git", "commit", "-m", "chore: init test project"],
        cwd=project_dir,
        check=True,
        capture_output=True,
        text=True,
        env=env,
    )


def create_test_project(tmp_path: Path) -> tuple[Path, dict[str, str]]:
    project_dir = tmp_path / "project"
    project_dir.mkdir()
    (project_dir / "logs").mkdir()
    (project_dir / ".ralph" / "memory").mkdir(parents=True)

    tasks = {
        "version": 1,
        "project": "integration-test",
        "phases": {"R1": {"name": "Reliability", "description": "Integration tests"}},
        "tasks": [
            {
                "id": "T01",
                "phase": "R1",
                "title": "Integration test task",
                "description": "Exercise prompt builder for context injection and keyword snippets",
                "status": "pending",
                "priority": "high",
                "dependencies": [],
                "timeout": 5,
            }
        ],
    }
    (project_dir / "tasks.json").write_text(json.dumps(tasks, indent=2), encoding="utf-8")
    (project_dir / "progress.md").write_text("# Progress\n", encoding="utf-8")
    (project_dir / "AGENTS.md").write_text("# AGENTS\n", encoding="utf-8")
    (project_dir / "ARCHITECTURE.md").write_text("# Architecture\n", encoding="utf-8")
    (project_dir / "MEMORY_SYSTEM.md").write_text("# Memory\n", encoding="utf-8")
    (project_dir / "AGENTS_CODER.md").write_text("# Coder\n", encoding="utf-8")
    (project_dir / "AGENTS_LEAD.md").write_text("# Lead\n", encoding="utf-8")
    (project_dir / ".ralph" / "memory" / "core.md").write_text("# Core\n", encoding="utf-8")
    (project_dir / ".ralph" / "memory" / "recent.md").write_text("# Recent\n", encoding="utf-8")
    (project_dir / "Makefile").write_text(".PHONY: test\n\ntest:\n\t@true\n", encoding="utf-8")
    (project_dir / "src").mkdir()
    (project_dir / "src" / "prompt_builder.ts").write_text(
        "export function buildKeywordPrompt() {\n"
        "  return 'context injection keyword matching prompt builder "
        + ("alpha " * 120)
        + "';\n"
        "}\n",
        encoding="utf-8",
    )

    bin_dir = tmp_path / "bin"
    bin_dir.mkdir()
    make_fake_binaries(bin_dir)

    init_git_repo(project_dir)

    env = os.environ.copy()
    env["PATH"] = f"{bin_dir}:{env['PATH']}"
    env["PYTHONUNBUFFERED"] = "1"
    env["RALPH_PROJECT_DIR"] = str(project_dir)
    env["RALPH_TELEGRAM_TOKEN"] = ""
    env["RALPH_TELEGRAM_CHAT_ID"] = ""
    env["MOCK_CODEX_WRITE_FILE"] = "src/generated_by_codex.ts"
    env["MOCK_CODEX_WRITE_CONTENT"] = "export const generatedByCodex = true;\\n"
    return project_dir, env


def load_task_status(project_dir: Path, task_id: str = "T01") -> str:
    data = json.loads((project_dir / "tasks.json").read_text(encoding="utf-8"))
    for task in data["tasks"]:
        if task["id"] == task_id:
            return task["status"]
    raise AssertionError(f"Task {task_id} not found")


def load_tasks(project_dir: Path) -> dict:
    return json.loads((project_dir / "tasks.json").read_text(encoding="utf-8"))


def write_tasks(project_dir: Path, data: dict) -> None:
    (project_dir / "tasks.json").write_text(json.dumps(data, indent=2), encoding="utf-8")


def load_state(project_dir: Path) -> dict:
    return json.loads((project_dir / "ralph_state.json").read_text(encoding="utf-8"))


def load_audit(project_dir: Path, task_id: str = "T01") -> dict:
    return json.loads((project_dir / ".ralph" / "audit" / f"{task_id}.json").read_text(encoding="utf-8"))


def process_is_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def test_ralph_marks_task_done_on_success(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    prompt_file = tmp_path / "coder_prompt.txt"
    env["MOCK_CODEX_CAPTURE_PROMPT_FILE"] = str(prompt_file)
    env["RALPH_CONTEXT_MAX_CHARS"] = "320"
    env["RALPH_CODER_PROMPT_MAX_CHARS"] = "2200"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "verified_done"
    prompt = prompt_file.read_text(encoding="utf-8")
    assert "## AGENTS.md Context" in prompt
    assert "# AGENTS" in prompt
    assert "## Relevant Source Snippets" in prompt
    assert "src/prompt_builder.ts" in prompt
    assert "export function buildKeywordPrompt()" in prompt
    assert "keyword matching prompt builder" in prompt
    assert "... [truncated" in prompt
    assert len(prompt) <= 2200 + 32
    assert "Commit: feat(" not in prompt
    assert "Ralph runtime owns final task bookkeeping" in prompt
    audit = load_audit(project_dir)
    assert audit["status"] == "done"
    assert audit["verification"]["result"] == "pass"
    assert audit["runtime_success"] is True
    assert audit["verified_success"] is True
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_task"] == ""
    assert state["current_phase_step"] == "completed"
    assert state["message"] == "Task T01 complete"


def test_ralph_task_mode_finalizes_idle_state_without_false_queue_completion(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"].append(
        {
            "id": "T02",
            "phase": "R1",
            "title": "Second pending task",
            "description": "Should remain pending after explicit single-task run",
            "status": "pending",
            "priority": "medium",
            "dependencies": [],
            "timeout": 5,
        }
    )
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "unbound variable" not in (result.stdout + result.stderr)
    assert "REASON" not in result.stderr
    assert load_task_status(project_dir, "T01") == "verified_done"
    assert load_task_status(project_dir, "T02") == "pending"
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_task"] == ""
    assert state["current_phase_step"] == "completed"
    assert state["message"] == "Task T01 complete"
    assert "All tasks complete" not in state["message"]


def test_ralph_task_success_final_tail_does_not_run_nested_status_pytest(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    python_shim = tmp_path / "bin" / "python3"
    write_executable(
        python_shim,
        f"""#!/usr/bin/env bash
if [ "${{1:-}}" = "-m" ] && [ "${{2:-}}" = "pytest" ] && [ "${{3:-}}" = "--tb=no" ] && [ "${{4:-}}" = "-q" ]; then
    echo "status pytest should not run during final tail" >&2
    exit 97
fi
exec "{sys.executable}" "$@"
""",
    )

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "verified_done"
    assert "syntax error" not in (result.stdout + result.stderr)
    assert "unexpected token" not in (result.stdout + result.stderr)
    assert "=== Final State ===" in result.stdout
    assert "Status: idle" in result.stdout
    assert "Step: completed" in result.stdout
    assert "Task T01 complete" in result.stdout
    assert "status pytest should not run during final tail" not in (result.stdout + result.stderr)
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_task"] == ""
    assert state["current_phase_step"] == "completed"
    assert state["message"] == "Task T01 complete"


def test_ralph_task_success_preserves_final_state_if_success_tail_reporting_hits_formatter_error(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    python_shim = tmp_path / "bin" / "python3"
    write_executable(
        python_shim,
        f"""#!/usr/bin/env bash
if [ "${{1:-}}" = "-c" ] && printf '%s' "${{2:-}}" | grep -Fq "* 3 / 1000000"; then
    echo "forced estimate_cost failure" >&2
    exit 91
fi
exec "{sys.executable}" "$@"
""",
    )

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "verified_done"
    assert "forced estimate_cost failure" not in (result.stdout + result.stderr)
    assert "=== Final State ===" in result.stdout
    assert "Status: idle" in result.stdout
    assert "Step: completed" in result.stdout
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_task"] == ""
    assert state["current_phase_step"] == "completed"
    assert state["message"] == "Task T01 complete"


def test_ralph_task_mode_runs_requested_pending_task_exactly(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Higher priority task that should not run",
            "description": "Must stay pending when T02 is explicitly requested",
            "status": "pending",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        },
        {
            "id": "T02",
            "phase": "R1",
            "title": "Explicitly requested task",
            "description": "Should run in task mode",
            "status": "pending",
            "priority": "low",
            "dependencies": [],
            "timeout": 5,
        },
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "task", "T02"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🎯 Requested task T02 is runnable and will be executed directly" in result.stdout
    assert "📋 Task: T02 — Explicitly requested task" in result.stdout
    assert load_task_status(project_dir, "T02") == "verified_done"
    assert load_task_status(project_dir, "T01") == "pending"


def test_ralph_handoff_mode_closes_from_existing_worktree_state_without_coder_run(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"][0]["title"] = "Minimal script task"
    tasks["tasks"][0]["description"] = "Add scripts/run_eval.py and keep it importable."
    tasks["tasks"][0]["acceptance_criteria"] = [
        "scripts/run_eval.py exists and is safely executable or importable"
    ]
    write_tasks(project_dir, tasks)

    (project_dir / "scripts").mkdir(exist_ok=True)
    (project_dir / "src" / "ralph" / "resources" / "scripts").mkdir(parents=True, exist_ok=True)
    (project_dir / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    (project_dir / "src" / "ralph" / "resources" / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🪄 HANDOFF — Using existing task-scoped worktree evidence" in result.stdout
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" in result.stdout
    assert load_task_status(project_dir) == "verified_done"
    audit = load_audit(project_dir)
    assert audit["status"] == "done"
    assert audit["verification"]["result"] == "pass"
    assert audit["runtime_success"] is True
    assert audit["verified_success"] is True
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_task"] == ""
    assert state["current_phase_step"] == "completed"
    assert state["message"] == "Task T01 complete"


def test_ralph_handoff_ignores_runtime_owned_dirty_artifacts_without_opening_candidate_path(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    audit_dir = project_dir / ".ralph" / "audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    (audit_dir / "T99.json").write_text('{"status":"done"}\n', encoding="utf-8")

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" not in result.stdout
    assert "Runtime-owned artifacts do not count" in result.stdout
    assert load_task_status(project_dir) == "blocked"
    audit = load_audit(project_dir)
    assert audit["status"] == "blocked"
    assert audit["runtime_success"] is False
    assert audit["verified_success"] is False


def test_ralph_handoff_mode_closes_from_repo_backed_candidate_state_without_coder_run(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"][0]["title"] = "Minimal script task"
    tasks["tasks"][0]["description"] = "Add scripts/run_eval.py and keep it importable."
    tasks["tasks"][0]["acceptance_criteria"] = [
        "scripts/run_eval.py exists and is safely executable or importable"
    ]
    write_tasks(project_dir, tasks)

    (project_dir / "scripts").mkdir(exist_ok=True)
    (project_dir / "src" / "ralph" / "resources" / "scripts").mkdir(parents=True, exist_ok=True)
    (project_dir / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    (project_dir / "src" / "ralph" / "resources" / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True, text=True)
    subprocess.run(
        ["git", "commit", "-m", "feat: repo-backed candidate"],
        cwd=project_dir,
        check=True,
        capture_output=True,
        text=True,
    )

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🪄 HANDOFF — Using repo-backed candidate state from commit" in result.stdout
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" in result.stdout
    assert load_task_status(project_dir) == "verified_done"
    audit = load_audit(project_dir)
    assert audit["status"] == "done"
    assert audit["verification"]["result"] == "pass"
    assert audit["runtime_success"] is True
    assert audit["verified_success"] is True
    state = load_state(project_dir)
    assert state["status"] == "idle"
    assert state["current_phase_step"] == "completed"


def test_ralph_handoff_mode_can_use_earlier_repo_backed_candidate_commit_even_with_unrelated_later_commit(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"][0]["title"] = "Minimal script task"
    tasks["tasks"][0]["description"] = "Add scripts/run_eval.py and keep it importable."
    tasks["tasks"][0]["acceptance_criteria"] = [
        "scripts/run_eval.py exists and is safely executable or importable"
    ]
    write_tasks(project_dir, tasks)

    (project_dir / "scripts").mkdir(exist_ok=True)
    (project_dir / "src" / "ralph" / "resources" / "scripts").mkdir(parents=True, exist_ok=True)
    text = "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n"
    (project_dir / "scripts" / "run_eval.py").write_text(text, encoding="utf-8")
    (project_dir / "src" / "ralph" / "resources" / "scripts" / "run_eval.py").write_text(text, encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=project_dir, check=True, capture_output=True, text=True)
    subprocess.run(
        ["git", "commit", "-m", "feat: exact candidate commit"],
        cwd=project_dir,
        check=True,
        capture_output=True,
        text=True,
    )
    (project_dir / "ARCHITECTURE.md").write_text("# Architecture\nLater unrelated commit\n", encoding="utf-8")
    subprocess.run(["git", "add", "ARCHITECTURE.md"], cwd=project_dir, check=True, capture_output=True, text=True)
    subprocess.run(
        ["git", "commit", "-m", "docs: unrelated later commit"],
        cwd=project_dir,
        check=True,
        capture_output=True,
        text=True,
    )

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🪄 HANDOFF — Using repo-backed candidate state from commit" in result.stdout
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" in result.stdout
    assert load_task_status(project_dir) == "verified_done"
    audit = load_audit(project_dir)
    assert audit["status"] == "done"
    assert audit["verification"]["result"] == "pass"
    assert audit["runtime_success"] is True
    assert audit["verified_success"] is True


def test_ralph_handoff_fail_closes_without_worktree_or_repo_backed_candidate_state(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" not in result.stdout
    assert "no task-scoped worktree evidence or exact-task repo-backed candidate evidence was found" in result.stdout
    assert load_task_status(project_dir) == "blocked"
    audit = load_audit(project_dir)
    assert audit["status"] == "blocked"
    assert audit["runtime_success"] is False
    assert audit["verified_success"] is False


def test_ralph_handoff_fail_closes_when_valid_task_evidence_is_contaminated_by_unrelated_tracked_changes(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"][0]["title"] = "Minimal script task"
    tasks["tasks"][0]["description"] = "Add scripts/run_eval.py and keep it importable."
    tasks["tasks"][0]["acceptance_criteria"] = [
        "scripts/run_eval.py exists and is safely executable or importable"
    ]
    write_tasks(project_dir, tasks)

    (project_dir / "scripts").mkdir(exist_ok=True)
    (project_dir / "src" / "ralph" / "resources" / "scripts").mkdir(parents=True, exist_ok=True)
    (project_dir / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    (project_dir / "src" / "ralph" / "resources" / "scripts" / "run_eval.py").write_text(
        "def main():\n    return 0\n\nif __name__ == '__main__':\n    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    (project_dir / "ARCHITECTURE.md").write_text("# Architecture\nUnrelated tracked change\n", encoding="utf-8")

    result = subprocess.run(
        [str(RALPH_SH), "handoff", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "🪄 HANDOFF — Evaluating existing task-scoped candidate state" in result.stdout
    assert "unrelated tracked changes outside the exact task scope" in result.stdout
    assert "ARCHITECTURE.md" in result.stdout
    assert "🤖 CODER — Attempt" not in result.stdout
    assert "👔 TECH LEAD — Reviewing" not in result.stdout
    assert load_task_status(project_dir) == "blocked"
    audit = load_audit(project_dir)
    assert audit["status"] == "blocked"
    assert audit["runtime_success"] is False
    assert audit["verified_success"] is False


def test_ralph_task_mode_rejects_non_runnable_requested_task_explicitly(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Independent runnable task",
            "description": "Would be next in auto mode",
            "status": "pending",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        },
        {
            "id": "T02",
            "phase": "R1",
            "title": "Blocked explicit task",
            "description": "Should not fall back to T01",
            "status": "pending",
            "priority": "low",
            "dependencies": ["T99"],
            "timeout": 5,
        },
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "task", "T02"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode != 0
    assert "Requested task T02 is not runnable: unmet dependencies: T99" in result.stdout
    assert "📋 Task:" not in result.stdout
    assert load_task_status(project_dir, "T02") == "pending"
    assert load_task_status(project_dir, "T01") == "pending"


def test_ralph_phase_mode_only_runs_pending_task_from_requested_phase(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["phases"]["R2"] = {"name": "Phase 2", "description": "Phase selection test"}
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Phase R1 task",
            "description": "Must stay pending when phase R2 is requested",
            "status": "pending",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        },
        {
            "id": "T02",
            "phase": "R2",
            "title": "Phase R2 task",
            "description": "Should run in phase mode",
            "status": "pending",
            "priority": "low",
            "dependencies": [],
            "timeout": 5,
        },
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "phase", "R2"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "📋 Task: T02 — Phase R2 task" in result.stdout
    assert load_task_status(project_dir, "T02") == "verified_done"
    assert load_task_status(project_dir, "T01") == "pending"


def test_ralph_auto_mode_still_runs_next_runnable_pending_task(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Blocked high priority task",
            "description": "Must not run because dependency is unmet",
            "status": "pending",
            "priority": "high",
            "dependencies": ["T99"],
            "timeout": 5,
        },
        {
            "id": "T02",
            "phase": "R1",
            "title": "Runnable medium priority task",
            "description": "Should run in auto mode",
            "status": "pending",
            "priority": "medium",
            "dependencies": [],
            "timeout": 5,
        },
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "auto"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "📋 Task: T02 — Runnable medium priority task" in result.stdout
    assert load_task_status(project_dir, "T02") == "verified_done"
    assert load_task_status(project_dir, "T01") == "pending"


def test_ralph_phase_mode_explains_deadlocked_pending_tasks(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["phases"]["R2"] = {"name": "Phase 2", "description": "Deadlock explanation test"}
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R2",
            "title": "Blocked in phase",
            "description": "Should not be reported as phase complete",
            "status": "pending",
            "priority": "high",
            "dependencies": ["T99"],
            "timeout": 5,
        }
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "phase", "R2"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Phase R2 deadlocked: pending tasks remain blocked by dependencies: T01" in result.stdout
    assert "Phase R2 blocked details: T01 needs T99" in result.stdout
    assert "Phase R2 complete!" not in result.stdout
    assert "No runnable tasks remain in Phase R2; pending tasks are blocked." in result.stdout
    assert load_task_status(project_dir, "T01") == "pending"
    state = load_state(project_dir)
    assert state["current_phase_step"] == "deadlocked"
    assert state["message"] == "Phase R2 deadlocked: pending tasks remain blocked by dependencies: T01"


def test_ralph_auto_mode_explains_deadlocked_pending_tasks(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Blocked in auto",
            "description": "Should not be reported as pure queue exhaustion",
            "status": "pending",
            "priority": "high",
            "dependencies": ["T99"],
            "timeout": 5,
        }
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "auto"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Auto deadlocked: pending tasks remain blocked by dependencies: T01" in result.stdout
    assert "Auto blocked details: T01 needs T99" in result.stdout
    assert "No runnable tasks remain; pending tasks are blocked." in result.stdout
    assert load_task_status(project_dir, "T01") == "pending"
    state = load_state(project_dir)
    assert state["current_phase_step"] == "deadlocked"
    assert state["message"] == "Auto deadlocked: pending tasks remain blocked by dependencies: T01"


def test_ralph_phase_mode_marks_final_state_deadlocked_after_last_runnable_task(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["phases"]["R2"] = {"name": "Phase 2", "description": "Mixed runnable and blocked"}
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R2",
            "title": "Runnable first",
            "description": "Should complete before deadlock is detected",
            "status": "pending",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        },
        {
            "id": "T02",
            "phase": "R2",
            "title": "Blocked after first task",
            "description": "Should keep phase from reporting completion",
            "status": "pending",
            "priority": "medium",
            "dependencies": ["T99"],
            "timeout": 5,
        },
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "phase", "R2"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "║ ✅ TASK COMPLETE" in result.stdout
    assert "Phase R2 deadlocked: pending tasks remain blocked by dependencies: T02" in result.stdout
    assert "Phase R2 blocked details: T02 needs T99" in result.stdout
    assert "Phase R2 complete!" not in result.stdout
    assert load_task_status(project_dir, "T01") == "verified_done"
    assert load_task_status(project_dir, "T02") == "pending"
    state = load_state(project_dir)
    assert state["current_phase_step"] == "deadlocked"
    assert state["message"] == "Phase R2 deadlocked: pending tasks remain blocked by dependencies: T02"


def test_ralph_auto_mode_does_not_report_complete_when_only_blocked_statuses_remain(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R1",
            "title": "Blocked backlog item",
            "description": "Should keep auto mode from reporting completion",
            "status": "blocked",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        }
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "auto"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "All tasks complete" not in result.stdout
    assert "Auto blocked by status: T01(blocked)" in result.stdout
    assert "Auto status details: T01 status=blocked" in result.stdout
    assert "No runnable tasks remain; unresolved tasks are blocked by status." in result.stdout
    state = load_state(project_dir)
    assert state["current_phase_step"] == "deadlocked"
    assert state["message"] == "Auto blocked: unresolved tasks remain non-runnable by status: T01(blocked)"


def test_ralph_phase_mode_does_not_report_complete_when_only_blocked_statuses_remain(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks = load_tasks(project_dir)
    tasks["phases"]["R2"] = {"name": "Phase 2", "description": "Blocked status exhaustion"}
    tasks["tasks"] = [
        {
            "id": "T01",
            "phase": "R2",
            "title": "Blocked phase item",
            "description": "Should keep phase mode from reporting completion",
            "status": "failed",
            "priority": "high",
            "dependencies": [],
            "timeout": 5,
        }
    ]
    write_tasks(project_dir, tasks)

    result = subprocess.run(
        [str(RALPH_SH), "phase", "R2"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Phase R2 complete!" not in result.stdout
    assert "Phase R2 blocked by status: T01(failed)" in result.stdout
    assert "Phase R2 status details: T01 status=failed" in result.stdout
    assert "No runnable tasks remain in Phase R2; unresolved tasks are blocked by status." in result.stdout
    state = load_state(project_dir)
    assert state["current_phase_step"] == "deadlocked"
    assert state["message"] == "Phase R2 blocked: unresolved tasks remain non-runnable by status: T01(failed)"


def test_ralph_blocks_duplicate_launch_with_pid_guard(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_SLEEP"] = "4"

    first = subprocess.Popen(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    assert wait_until(lambda: (project_dir / "ralph_main.pid").exists(), timeout=10)

    second = subprocess.run(
        [str(RALPH_SH), "auto"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=10,
    )

    first.terminate()
    try:
        first.communicate(timeout=10)
    except subprocess.TimeoutExpired:
        first.kill()
        first.communicate(timeout=10)

    assert second.returncode != 0
    assert "Ralph already running" in second.stdout


def test_ralph_uses_complexity_default_timeout_when_timeout_missing(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks_path = project_dir / "tasks.json"
    tasks = json.loads(tasks_path.read_text(encoding="utf-8"))
    tasks["tasks"][0].pop("timeout", None)
    tasks["tasks"][0]["complexity"] = "complex"
    tasks_path.write_text(json.dumps(tasks, indent=2), encoding="utf-8")

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Timeout: coder=600s lead=300s" in result.stdout


def test_ralph_retries_after_fix_and_then_marks_done(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "lead_fix_once"
    env["MOCK_LEAD_FIX_MARKER"] = str(tmp_path / "lead_fix.marker")

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "verified_done"
    assert "🔧 Fix 1/2:" in result.stdout
    assert result.stdout.count("🤖 CODER — Attempt") >= 2
    assert "👔 Decision: approve" in result.stdout


def test_ralph_fails_closed_on_lead_stdout_review_mismatch(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "lead_mismatch_fix"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "blocked"
    assert "Parsed review source: mismatch_fail_closed" in result.stdout
    assert "ambiguous: authoritative review file and stdout disagreed" in result.stdout


def test_ralph_blocks_contradictory_bookkeeping_only_fix_instructions(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "lead_contradictory_fix_only"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "blocked"
    assert "Contradictory Tech Lead fix blocked retry" in result.stdout
    assert "runtime-owned bookkeeping or diff-production work" in result.stdout
    assert result.stdout.count("🤖 CODER — Attempt") == 1


def test_ralph_blocks_diff_only_fix_without_retry_loop(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "lead_diff_only_fix"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "blocked"
    assert "Contradictory Tech Lead fix blocked retry" in result.stdout
    assert "runtime-owned bookkeeping or diff-production work" in result.stdout
    assert result.stdout.count("🤖 CODER — Attempt") == 1


def test_ralph_sanitizes_noisy_fix_and_keeps_exact_feature_gap(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "lead_exact_gap_with_bookkeeping_noise"
    env["MOCK_LEAD_FIX_MARKER"] = str(tmp_path / "lead_exact_gap.marker")
    prompt_file = tmp_path / "coder_prompt_fix.txt"
    env["MOCK_CODEX_CAPTURE_PROMPT_FILE"] = str(prompt_file)

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Sanitized Tech Lead fix instructions" in result.stdout
    assert "Add an /audit_task alias that routes to the single-task audit handler and cover it with a bot test." in result.stdout
    assert "tasks.json" not in result.stdout.split("🔧 Fix 1/2:", 1)[1].splitlines()[0]
    assert "progress.md" not in result.stdout.split("🔧 Fix 1/2:", 1)[1].splitlines()[0]
    assert "real git diff" not in result.stdout.split("🔧 Fix 1/2:", 1)[1].splitlines()[0]
    prompt = prompt_file.read_text(encoding="utf-8")
    assert "Add an /audit_task alias that routes to the single-task audit handler and cover it with a bot test." in prompt
    assert "update tasks.json" not in prompt
    assert "update progress.md" not in prompt
    assert "real git diff" not in prompt


def test_ralph_blocks_bookkeeping_only_closure(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_WRITE_FILE"] = "progress.md"
    env["MOCK_CODEX_WRITE_CONTENT"] = "\nbookkeeping-only change\n"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "blocked"
    assert "Verification failed: only bookkeeping/state/report files changed" in result.stdout
    audit = load_audit(project_dir)
    assert audit["status"] == "blocked"
    assert audit["verification"]["result"] == "fail_fix"
    assert audit["runtime_success"] is True
    assert audit["verified_success"] is False


def test_ralph_allows_docs_only_task_with_docs_evidence(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    tasks_path = project_dir / "tasks.json"
    tasks = json.loads(tasks_path.read_text(encoding="utf-8"))
    tasks["tasks"][0]["title"] = "Docs: trust layer note"
    tasks["tasks"][0]["description"] = "Update docs/TRUST_LAYER.md with a short note."
    tasks["tasks"][0]["acceptance_criteria"] = ["docs/TRUST_LAYER.md exists"]
    tasks_path.write_text(json.dumps(tasks, indent=2), encoding="utf-8")
    (project_dir / "docs").mkdir(exist_ok=True)
    env["MOCK_CODEX_WRITE_FILE"] = "docs/TRUST_LAYER.md"
    env["MOCK_CODEX_WRITE_CONTENT"] = "# Trust Layer\n"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert load_task_status(project_dir) == "verified_done"
    assert "🧪 Verification: pass (docs-only)" in result.stdout


def test_ralph_audit_cli_prints_expected_fields(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)

    run_result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr

    audit_result = subprocess.run(
        [str(RALPH_SH), "audit", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert audit_result.returncode == 0, audit_result.stdout + audit_result.stderr
    assert "Audit: T01 — done" in audit_result.stdout
    assert "Verification: pass" in audit_result.stdout
    assert "Evidence files:" in audit_result.stdout
    assert "Duration:" in audit_result.stdout


def test_ralph_trust_report_aggregates_audit_artifacts(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    audit_dir = project_dir / ".ralph" / "audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    (audit_dir / "T01.json").write_text(
        json.dumps(
            {
                "task_id": "T01",
                "title": "Task 1",
                "status": "done",
                "verification": {"result": "pass", "reason": "", "task_class": "implementation", "evidence_files": ["src/a.ts"]},
                "changes": {"all": ["src/a.ts"], "non_bookkeeping": ["src/a.ts"]},
                "review": {"raw": "{}", "parsed": {"decision": "approve"}},
                "attempts": 1,
                "duration_sec": 5,
                "timestamp": "2026-03-17T00:00:00Z",
                "runtime_success": True,
                "verified_success": True,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (audit_dir / "T02.json").write_text(
        json.dumps(
            {
                "task_id": "T02",
                "title": "Task 2",
                "status": "blocked",
                "verification": {"result": "fail_fix", "reason": "missing file", "task_class": "script", "evidence_files": []},
                "changes": {"all": ["progress.md"], "non_bookkeeping": []},
                "review": {"raw": "{}", "parsed": {"decision": "approve"}},
                "attempts": 2,
                "duration_sec": 9,
                "timestamp": "2026-03-17T00:01:00Z",
                "runtime_success": True,
                "verified_success": False,
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    result = subprocess.run(
        [str(RALPH_SH), "trust-report"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Total tasks: 2" in result.stdout
    assert "Verified success: 1" in result.stdout
    assert "Runtime success only: 1" in result.stdout
    assert "Invalid artifacts: 0" in result.stdout


def test_ralph_audit_last_lists_recent_tasks(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    audit_dir = project_dir / ".ralph" / "audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    for idx, ts in enumerate(["2026-03-17T00:00:00Z", "2026-03-17T00:01:00Z", "2026-03-17T00:02:00Z"], start=1):
        (audit_dir / f"T0{idx}.json").write_text(
            json.dumps(
                {
                    "task_id": f"T0{idx}",
                    "title": f"Task {idx}",
                    "status": "done" if idx != 2 else "blocked",
                    "verification": {"result": "pass" if idx != 2 else "fail_fix", "reason": f"reason {idx}", "task_class": "implementation", "evidence_files": []},
                    "changes": {"all": ["src/file.ts"], "non_bookkeeping": ["src/file.ts"]},
                    "review": {"raw": "{}", "parsed": {"decision": "approve"}},
                    "attempts": idx,
                    "duration_sec": 5 + idx,
                    "timestamp": ts,
                    "runtime_success": True,
                    "verified_success": idx != 2,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    result = subprocess.run(
        [str(RALPH_SH), "audit-last", "2"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "=== Last 2 audit tasks ===" in result.stdout
    assert "T03 | done | pass | runtime=True | verified=True | reason 3" in result.stdout
    assert "T02 | blocked | fail_fix | runtime=True | verified=False | reason 2" in result.stdout
    assert "T01" not in result.stdout


def test_ralph_reporting_survives_malformed_audit_artifact(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    audit_dir = project_dir / ".ralph" / "audit"
    audit_dir.mkdir(parents=True, exist_ok=True)
    (audit_dir / "T01.json").write_text(
        json.dumps(
            {
                "task_id": "T01",
                "title": "Task 1",
                "status": "done",
                "verification": {"result": "pass", "reason": "", "task_class": "implementation", "evidence_files": ["src/a.ts"]},
                "changes": {"all": ["src/a.ts"], "non_bookkeeping": ["src/a.ts"]},
                "review": {"raw": "{}", "parsed": {"decision": "approve"}},
                "attempts": 1,
                "duration_sec": 5,
                "timestamp": "2026-03-17T00:00:00Z",
                "runtime_success": True,
                "verified_success": True,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    (audit_dir / "BROKEN.json").write_text("{not-json", encoding="utf-8")

    list_result = subprocess.run(
        [str(RALPH_SH), "audit-last", "5"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )
    report_result = subprocess.run(
        [str(RALPH_SH), "trust-report"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert list_result.returncode == 0, list_result.stdout + list_result.stderr
    assert "BROKEN | invalid | invalid | runtime=False | verified=False | Malformed audit artifact:" in list_result.stdout
    assert "Invalid artifacts skipped into report output: 1" in list_result.stdout

    assert report_result.returncode == 0, report_result.stdout + report_result.stderr
    assert "Total tasks: 2" in report_result.stdout
    assert "Verified success: 1" in report_result.stdout
    assert "Invalid artifacts: 1" in report_result.stdout


def test_ralph_marks_task_skipped_on_skip_control(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_SLEEP"] = "1.5"

    process = subprocess.Popen(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    state_file = project_dir / "ralph_state.json"
    assert wait_until(
        lambda: state_file.exists() and load_state(project_dir).get("current_phase_step") == "coder",
        timeout=20,
    )

    (project_dir / "ralph_control.json").write_text(
        json.dumps({"action": "skip", "comment": "T01"}, indent=2),
        encoding="utf-8",
    )

    stdout, _ = process.communicate(timeout=20)
    assert process.returncode == 0, stdout
    assert load_task_status(project_dir) == "skipped"


def test_ralph_stops_when_stop_control_is_present(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    (project_dir / "ralph_control.json").write_text(
        json.dumps({"action": "stop", "comment": ""}, indent=2),
        encoding="utf-8",
    )

    result = subprocess.run(
        [str(RALPH_SH), "auto"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=20,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    state = load_state(project_dir)
    assert state["status"] == "stopped"
    assert load_task_status(project_dir) == "pending"


def test_ralph_watchdog_kills_stale_codex_and_retries(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_SLEEP"] = "3"
    env["RALPH_WATCHDOG_TIMEOUT"] = "1"
    env["RALPH_CODEX_RETRY_DELAYS"] = "0 0 0"

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert result.returncode != 0, result.stdout + result.stderr
    assert result.stdout.count("Watchdog timeout - killing stale codex process") >= 2
    assert "Codex failed after 3 retries" in result.stdout


def test_ralph_pauses_and_retries_on_rate_limit(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "rate_limit_once"
    env["MOCK_RATE_LIMIT_MARKER"] = str(tmp_path / "rate_limit.marker")
    env["RALPH_RATE_LIMIT_PAUSE"] = "1"
    env["RALPH_CODEX_RETRY_DELAYS"] = "0 0 0"

    process = subprocess.Popen(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    stdout, _ = process.communicate(timeout=30)
    assert process.returncode == 0, stdout
    assert "RATE LIMIT detected" in stdout
    assert load_task_status(project_dir) == "verified_done"


def test_ralph_timeout_cleans_up_orphan_children(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "timeout_child"
    env["MOCK_CHILD_PID_FILE"] = str(tmp_path / "codex_child.pid")
    env["MOCK_GTIMEOUT_KILL_PARENT_ONLY"] = "1"
    env["RALPH_CODEX_RETRY_DELAYS"] = "0 0 0"

    tasks_path = project_dir / "tasks.json"
    tasks = json.loads(tasks_path.read_text(encoding="utf-8"))
    tasks["tasks"][0]["timeout"] = 1
    tasks_path.write_text(json.dumps(tasks, indent=2), encoding="utf-8")

    result = subprocess.run(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        capture_output=True,
        text=True,
        timeout=45,
    )

    assert (tmp_path / "codex_child.pid").exists(), result.stdout + result.stderr
    child_pid = int((tmp_path / "codex_child.pid").read_text(encoding="utf-8"))
    assert result.returncode != 0, result.stdout + result.stderr
    assert "TIMEOUT: codex exceeded 1s" in result.stdout
    assert "Codex timed out after 3 retries" in result.stdout
    assert not process_is_alive(child_pid)


def test_ralph_waits_for_assets_and_resumes_when_files_arrive(tmp_path: Path) -> None:
    project_dir, env = create_test_project(tmp_path)
    env["MOCK_CODEX_MODE"] = "asset_manifest_wait"
    env["RALPH_ASSET_POLL_INTERVAL"] = "1"

    process = subprocess.Popen(
        [str(RALPH_SH), "task", "T01"],
        cwd=project_dir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )

    assert wait_until(lambda: (project_dir / "assets_manifest.json").exists(), timeout=20)

    inbox_file = project_dir / ".ralph" / "assets" / "inbox" / "hero-image.txt"
    inbox_file.parent.mkdir(parents=True, exist_ok=True)
    inbox_file.write_text("hero-image-binary", encoding="utf-8")

    stdout, _ = process.communicate(timeout=30)
    assert process.returncode == 0, stdout
    assert load_task_status(project_dir) == "verified_done"
    assert "assets_manifest.json" in stdout or "Assets ready for T01" in stdout or "Required assets are ready" in stdout
    assert not inbox_file.exists()
    assert (project_dir / "src" / "assets" / "hero-image.txt").read_text(encoding="utf-8") == "hero-image-binary"
